--- 
  theme: dirtyfrankez
  default_locale: pt
  addthis_pubid: "ra-4db0c70d4e7542c2"
  title: Associação de Taekwondo de Braga
  site_name: Associação de Taekwondo de Braga
  site_header: Associação de Taekwondo de Braga
  force_locale: "true"
