---
  theme: none
  default_locale: pt
  title: "Jovens sem Fronteiras"
  site_name: "Jovens sem Fronteiras"
  site_header: "Jovens sem Fronteiras"
  announcement_size: "910x270#"
  post_image_size: "640x200#"
  force_locale: "true"
